### ISSUE TITLE
Voir son commentaire sans recharger la page

### ISSUE THREAD

**Issue by ThomasEscorne** [faty-gass/bookclub_ecp#2]
Il aut recharger la page pour voir s'afficher le commentaire que l'on vient d'écrire, il faudrait que le message apparaisse sans devoir recharger la page

**Comment by ThomasEscorne** [comment]
Up

**Comment by faty-gass** [comment]
J'ai ajouté des événements permettant de recharger le composant parent dès que les data du child sont updatées.
Problème résolu.
